# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoZpl < Formula
  desc "A CLI tool for conversion of ZPL files."
  homepage "https://github.com/kamilturek/go-zpl"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kamilturek/go-zpl/releases/download/v0.0.6/go-zpl_0.0.6_Darwin_arm64.tar.gz"
      sha256 "e7fae1bb515fa48e6ff7b25a47421a02d45d5ef19142457ce24879c908844f90"

      def install
        bin.install "go-zpl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilturek/go-zpl/releases/download/v0.0.6/go-zpl_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "16f555e4903f9fefb0a3195763c0362666d1ab50e2b3f522738be1417ebd5c60"

      def install
        bin.install "go-zpl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kamilturek/go-zpl/releases/download/v0.0.6/go-zpl_0.0.6_Linux_x86_64.tar.gz"
      sha256 "f1bfe882a8b33c9a9e1b475528473827fd633334c40a1d30862b2fc2371da8bd"

      def install
        bin.install "go-zpl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilturek/go-zpl/releases/download/v0.0.6/go-zpl_0.0.6_Linux_arm64.tar.gz"
      sha256 "45436de46bd1d85ff2278dd9b87d797ba0b28a2a29c541bad95486c3f8601527"

      def install
        bin.install "go-zpl"
      end
    end
  end

  test do
    system "#{bin}/program --version"
  end
end
