# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoZpl < Formula
  desc "A CLI tool for conversion of ZPL files."
  homepage "https://github.com/kamilturek/go-zpl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamilturek/go-zpl/releases/download/v0.1.0/go-zpl_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "2d1c80b472dd06ec5b52b982483c7a49b4a9f51dd4e481967bbb2a66c7197f66"

      def install
        bin.install "go-zpl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamilturek/go-zpl/releases/download/v0.1.0/go-zpl_0.1.0_Darwin_arm64.tar.gz"
      sha256 "f1db7d5c25ad009c489d7203c131423e8a7a2904acdc077c615c94f887181fcc"

      def install
        bin.install "go-zpl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilturek/go-zpl/releases/download/v0.1.0/go-zpl_0.1.0_Linux_arm64.tar.gz"
      sha256 "6920dc5c366ef5b7a54576897bff12db29d5b6f04453836ecfa7a82035bcb7b9"

      def install
        bin.install "go-zpl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kamilturek/go-zpl/releases/download/v0.1.0/go-zpl_0.1.0_Linux_x86_64.tar.gz"
      sha256 "1d0410aee2185411790778f69228663ef21f30fba9004d5cf42ca22b586cf09b"

      def install
        bin.install "go-zpl"
      end
    end
  end

  test do
    system "#{bin}/program --version"
  end
end
